# Generated by Django 3.1.4 on 2020-12-18 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.TextField()),
                ('application_url', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.TextField(blank=True, null=True)),
                ('bundle_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.TextField()),
                ('developer_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.TextField()),
                ('person_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.TextField()),
                ('publisher_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HumbleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('claimed', models.BooleanField(default=False)),
                ('date_claimed', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humblebundle.application')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humblebundle.bundle')),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humblebundle.person')),
                ('developer', models.ManyToManyField(to='humblebundle.Developer')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humblebundle.publisher')),
            ],
        ),
    ]
