# Generated by Django 3.1.5 on 2021-01-28 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumbleBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.TextField(blank=True, null=True)),
                ('bundle_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HumbleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redemption_platform', models.TextField(help_text='Platform where code is redeemed, such as Steam or GOG')),
                ('date_added', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_gift', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('date_claimed', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.application')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humblestore.humblebundle')),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.person')),
                ('developer', models.ManyToManyField(to='core.Developer')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publisher')),
            ],
        ),
    ]
