# Generated by Django 3.1.4 on 2020-12-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.TextField(blank=True, null=True)),
                ('bundle_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HumbleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('claimed', models.BooleanField(default=False)),
                ('date_claimed', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.application')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humblestore.bundle')),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.person')),
                ('developer', models.ManyToManyField(to='core.Developer')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publisher')),
            ],
        ),
    ]
